// Code generated by "stringer -type=DownloadStatus"; DO NOT EDIT.

package entangler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoDownload-0]
	_ = x[DownloadPending-1]
	_ = x[DownloadSuccess-2]
	_ = x[DownloadFailed-3]
}

const _DownloadStatus_name = "NoDownloadDownloadPendingDownloadSuccessDownloadFailed"

var _DownloadStatus_index = [...]uint8{0, 10, 25, 40, 54}

func (i DownloadStatus) String() string {
	if i < 0 || i >= DownloadStatus(len(_DownloadStatus_index)-1) {
		return "DownloadStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DownloadStatus_name[_DownloadStatus_index[i]:_DownloadStatus_index[i+1]]
}
