// Code generated by "stringer -type=StrandClass"; DO NOT EDIT.

package entangler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Horizontal-0]
	_ = x[Right-1]
	_ = x[Left-2]
}

const _StrandClass_name = "HorizontalRightLeft"

var _StrandClass_index = [...]uint8{0, 10, 15, 19}

func (i StrandClass) String() string {
	if i < 0 || i >= StrandClass(len(_StrandClass_index)-1) {
		return "StrandClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StrandClass_name[_StrandClass_index[i]:_StrandClass_index[i+1]]
}
